### ISSUE TITLE
执行脚本build_snippets.py报错

### ISSUE THREAD

**Issue by FrizzleFur** [lettleprince/MyCodeSnippet#1]
Xcode 中9.4.1
执行脚本的时候报错如下：

```
Traceback (most recent call last):
  File "build_snippets.py", line 43, in <module>
    main()
  File "build_snippets.py", line 39, in main
    build_snippets()
  File "build_snippets.py", line 31, in build_snippets
    print('Rename %s to %s' % XCODE_SNIPPETS_DIR, BACKUP_DIR)
TypeError: not enough arguments for format string
```

**Comment by FrizzleFur** [comment]
脚本貌似在我的Xcode上执行有问题，我直接将代码段拷贝到CodeSnippets文件夹中了。
